---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plugin-site.fullname" . }}
  labels:
{{ include "plugin-site.labels" . | indent 4 }}
type: Opaque
data:
  github_app_id: {{ required "github.appId is required" .Values.github.appId | toString | b64enc }}
  github_app_key: {{ required "github.appPrivateKey is required" .Values.github.appPrivateKey | toString | b64enc }}
  jira_username: {{ required "jira.username is required" .Values.jira.username | b64enc }}
  jira_password: {{ required "jira.password is required" .Values.jira.password | b64enc }}
{{ if .Values.azureStorageAccountName }}
  azurestorageaccountname: {{ .Values.azureStorageAccountName | b64enc }}
{{- end }}
{{ if .Values.azureStorageAccountKey }}
  azurestorageaccountkey: {{ .Values.azureStorageAccountKey | b64enc }}
{{- end }}
{{- if .Values.sentry.dsn }}
  sentry_dsn: {{ .Values.sentry.dsn | b64enc }}
{{- end }}
