{{ if .Values.azureStorageAccountName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jenkinsio
type: Opaque
data:
  azurestorageaccountname: {{ .Values.azureStorageAccountName | b64enc }}
  azurestorageaccountkey: {{ .Values.azureStorageAccountKey | b64enc }}
{{- end }}