apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "javadoc.fullname" . }}
  labels: {{ include "javadoc.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen       80;
      server_name  localhost;
      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
          autoindex on;
      }
    }