---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ldap.fullname" . }}
  labels:
{{ include "ldap.labels" . | indent 4 }}
type: Opaque
data:
  azurestorageaccountname: {{ .Values.ldap.storage.accountname | b64enc }}
  azurestorageaccountkey: {{ .Values.ldap.storage.accountkey | b64enc }}
  ldap.admin.password: {{ .Values.ldap.admin.password | b64enc }}
