apiVersion: v1
kind: Service
metadata:
  name: {{ include "ldap.fullname" . }}
  labels:
{{ include "ldap.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- if .Values.service.IP }}
  loadBalancerIP: {{ .Values.service.IP }}
  {{- end }}
  loadBalancerSourceRanges: 
    {{- range .Values.service.whitelisted_sources }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  ports:
    - port: 636
      targetPort: 636
      name: ldaps
  selector:
    app.kubernetes.io/name: {{ include "ldap.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
