{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "ldap.serviceAccountName" . }}
  labels:
{{ include "ldap.labels" . | indent 4 }}
{{- end -}}
