---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "incrementals-publisher.fullname" . }}
  labels:
{{ include "incrementals-publisher.labels" . | indent 4 }}
type: Opaque
data:
  artifactory_key: {{ required "artifactory.key is required" .Values.artifactory.key | toString | b64enc }}
  github_token: {{ required "github.token is required" .Values.github.token | toString | b64enc }}
  jenkins_auth: {{ required "jenkins.auth is required" .Values.jenkins.auth | toString | b64enc }}
  preshared_key: {{ required "preshared_key is required" .Values.preshared_key | toString | b64enc }}
