{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "incrementals-publisher.serviceAccountName" . }}
  labels:
{{ include "incrementals-publisher.labels" . | indent 4 }}
{{- end -}}
