{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "mirrorbits.serviceAccountName" . }}
  labels:
{{ include "mirrorbits.labels" . | indent 4 }}
{{- end -}}
