---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "accountapp.fullname" . }}
  labels:
{{ include "accountapp.labels" . | indent 4 }}
type: Opaque
data:
  ldapPassword: {{ .Values.ldap.password | b64enc }}
  jiraPassword: {{ .Values.jira.password | b64enc }}
  smtpPassword: {{ .Values.smtp.password | b64enc }}
