{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "uplink.serviceAccountName" . }}
  labels:
{{ include "uplink.labels" . | indent 4 }}
{{- end -}}
